lenguage: generic
#le damos super usuario
sudo: required

#instala docker
services:
  -docker
#before
before_install:
  - docker build -t nschuz/ci -f Dockerfile.dev .

script:
  - docker run -e CI=true nschuz/ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  #toma los archivos de de gittbus y  sube los archivos al bucket
  bucket_name: "elasticbeanstalk-us-west-2-177760986445"
  #la primera vez utilizamos app name
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY